#!/bin/sh

DEB_NAME=kylin-kmre-modules-dkms
NAME=kylin-kmre-modules-dkms
VERSION=1.0

for kv in $(ls /lib/modules/ | egrep -e "^5\.|^6\."); do
    if [ -d /lib/modules/${kv}/build/ ]; then
        dkms install ${NAME}/${VERSION} -k ${kv} || echo ""
    fi
done

exit 0
